//
// Copy this file and name it secrets.js in your local environment and enter in the secret keys.
//
// !!! DO NOT CHECK-IN secrets.js (Note secrets.js is in .gitignore) !!!
//
// secrets.js is auto generated by .github/workflows/deploy.yml
// The Github secrets are injected in with the secrets as key/value pairs.
//
// Add secrets here to support a local dev environment.
//
// Add a helper function to access these in ./SecretsUtils.js
//
module.exports = {
  AWS_ACCESS_KEY_ID: 'FILL IN',
  AWS_SECRET_ACCESS_KEY: 'FILL IN'
}
