org: hutch120
app: one-at-the-wheel
service: one-at-the-wheel
frameworkVersion: '2'

custom:
  oneAtTheWheelBucketName: "one-at-the-wheel"

provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
  environment:
    ONE_AT_THE_WHEEL_BUCKET: ${self:custom.oneAtTheWheelBucketName}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
