org: polynize
app: one-at-the-wheel
service: one-at-the-wheel
frameworkVersion: '2'

provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
  environment:
    ONE_AT_THE_WHEEL_BUCKET: ${self:resources.Resources.oneAtTheWheel.Properties.BucketName}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

resources:
  Resources:
  oneAtTheWheel:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: one-at-the-wheel
