org: hutch120
app: one-at-the-wheel
service: one-at-the-wheel
frameworkVersion: '2'

provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
