# Remove org and app to avoid need for SERVERLESS_ACCESS_KEY 
# See https://github.com/serverless/github-action/issues/53 for more details.
org: hutch120 
app: one-at-the-wheel
service: one-at-the-wheel
frameworkVersion: '2'

provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::${self:resources.Resources.oneAtTheWheelData.Properties.BucketName}/*"
  environment:
    ONE_AT_THE_WHEEL_DATA_BUCKET: ${self:resources.Resources.oneAtTheWheelData.Properties.BucketName}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

resources:
  Resources:
    oneAtTheWheel:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: one-at-the-wheel
    oneAtTheWheelData:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: one-at-the-wheel-data