name: Deploy main branch serverless

on:
  push:
    branches:
      - main

jobs:
  deployclient:
    name: deployclient
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Configure AWS credentials from Production account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Generate config.js file
        run: |
          echo 'export const config = {' > ./src/config.js
          echo "VERSION: '`date +"%s"`'" >> ./src/config.js
          echo '}' >> ./src/config.js
      - name: Build site
        run: yarn && yarn build
      - name: Copy files to the production website with the AWS CLI
        run: aws s3 sync ./build s3://one-at-the-wheel --delete --exclude "*.map" --acl public-read
      - name: Clear cache oatw.hutchisonsoftware.com.au
        run: |
          aws cloudfront create-invalidation --distribution-id E227UTWMV9U9J4 --paths "/*"
