name: Deploy main branch serverless

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Server Build
      run: cd server

    - name: Generate secrets.js file
      run: echo "module.exports = { SERVERLESS_ACCESS_KEY${{':'}} \"${{ secrets.SERVERLESS_ACCESS_KEY }}\" }" > ./secrets.js

    - name: Load dependancies
      run: yarn

    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

    - name: Client Build
      run: cd ..

    - name: Configure AWS credentials from Production account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Build site
      run: yarn && yarn build

    - name: Copy files to the production website with the AWS CLI
      run: aws s3 sync ./build s3://one-at-the-wheel --delete --exclude "*.map" --acl public-read

    # - name: Clear cache one-at-the-wheel
    #  run: aws cloudfront create-invalidation --distribution-id E3G3NYT4OLNIFI --paths "/*"
